### ISSUE TITLE
Unrecognized mod

### ISSUE THREAD

**Issue by SpartannoO** [AMacro/dv-multiplayer#58]
- **Hello, when I load the game, the mod is red and not usable despite installing it correctly multiple times. I don't understand o_O. If you could help me, that would be nice :) :** 

Mono path[0] = 'G:/SteamLibrary/steamapps/common/Derail Valley/DerailValley_Data/Managed'
Mono config path = 'G:/SteamLibrary/steamapps/common/Derail Valley/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.40f1 (ffc62b691db5)
[Subsystems] Discovering subsystems at path G:/SteamLibrary/steamapps/common/Derail Valley/DerailValley_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3070 Ti (ID=0x2482)
    Vendor:   
    VRAM:     8018 MB
    Driver:   32.0.15.6614
Begin MonoManager ReloadAssembly

[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.31.1.0.
[Manager] OS: Microsoft Windows NT 10.0.22631.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.401.
[Manager] Game: Derail Valley.
[Manager] IsSupportOnSessionStart: True.
[Manager] IsSupportOnSessionStop: False.
[Manager] Mods path: G:\SteamLibrary\steamapps\common\Derail Valley\Mods.
Fallback handler could not load library G:/SteamLibrary/steamapps/common/Derail Valley/DerailValley_Data/Mono/data-00000186E4339030.dll
Fallback handler could not load library G:/SteamLibrary/steamapps/common/Derail Valley/DerailValley_Data/Mono/data-00000186E71CF1A0.dll
[Manager] Injection successful.
- Completed reload, in  0.477 seconds
<RI> Initializing input.
New input system (experimental) initialized
<RI> Input initialized.
<RI> Initialized touch support.
The referenced script on this Behaviour (Game Object '[init]') is missing! 
(Filename:  Line: 334)

UnloadTime: 0.568600 ms
[Globals] fetching default config from resources 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

The referenced script on this Behaviour (Game Object '[VR Collider]') is missing! 
(Filename:  Line: 334)

[Manager] Starting.
[Manager] Parsing mods.
[Manager] Reading file 'G:\SteamLibrary\steamapps\common\Derail Valley\Mods\dv-multiplayer-0.1.9.2-Beta\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[Multiplayer] Version '0.1.9.2'. Loading.
[Multiplayer] [Error] AssemblyName is null.
[Multiplayer] Optional mod 'RemoteDispatch' not found.
[Multiplayer] Loading time 0,00 s.
[Manager] FINISH. SUCCESSFUL LOADED 0/1 MODS.

**Comment by AMacro** [comment]
Hey @SpartannoO,

The issue here is you've tried to install the source code, not the compiled binaries.

To fix this, you will need to:

1. Open this folder: `G:\SteamLibrary\steamapps\common\Derail Valley\Mods\`
2. Delete the `dv-multiplayer-0.1.9.2-Beta` folder
3. Go to the [releases page](https://github.com/AMacro/dv-multiplayer/releases)
4. Open the latest release (at this time it is [v0.1.9.2-Beta](https://github.com/AMacro/dv-multiplayer/releases/tag/v0.1.9.2-Beta))
5. From the `Assets` section at the bottom, download the first zip file (not the source code files) 
![image](https://github.com/user-attachments/assets/ddad92df-d592-4696-845c-f0cae2cd40b0)
6. Install the downloaded file with UnityModManager Installer

**Comment by SpartannoO** [comment]
Merci beaucoup :) ça fonctionne !
